### ISSUE TITLE
gdb terminal input is corrupted

### ISSUE THREAD

**Issue by amathews-amd** [yugr/libdebugme#5]
Handy utility, but cannot seem to enter a command in the gdb prompt. 
```
(gdb) backtrace
Undefined command: "aa".  Try "help".
(gdb) backtrace
Undefined command: "crcacegob".  Try "help".
```

**Comment by yugr** [comment]
Thank you for trying libdebugme.

Is it possible to reproduce this behavior? I couldn't see corrupt input using this simple test on Ubuntu 20.04:
```
yugr@yugr-VirtualBox:~$ cat segv.c
int main(int argc, char *argv[]) {
  volatile int *ptr = 0;
  return *ptr;
}
yugr@yugr-VirtualBox:~$ gcc segv.c
yugr@yugr-VirtualBox:~$ ./a.out 
Segmentation fault (core dumped)
yugr@yugr-VirtualBox:~$ LD_PRELOAD=$HOME/src/my/libdebugme/bin/libdebugme.so DEBUGME_OPTIONS='handle_signals=1' ./a.out segv
...
Program received signal SIGTRAP, Trace/breakpoint trap.
debugme_debug (dbg_flags_=<optimized out>, dbg_opts_=<optimized out>) at src/debugme.c:111
111	  in_debugme_debug = 0;
(gdb) backtrace
#0  debugme_debug (dbg_flags_=<optimized out>, dbg_opts_=<optimized out>) at src/debugme.c:111
#1  0x00007ffbccea6d4c in sighandler (sig=<optimized out>) at src/debugme.c:31
#2  <signal handler called>
#3  0x00005580bc3fe144 in main ()
(gdb) 
```
